// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg44ubOgDW36LVKPl0nszJ0GopabSiACk',
    appId: '1:31010099352:web:a381d004d332ac07edc0ed',
    messagingSenderId: '31010099352',
    projectId: 'login-auth-eec5f',
    authDomain: 'login-auth-eec5f.firebaseapp.com',
    storageBucket: 'login-auth-eec5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRESr94wy-7g8Shz0RSvl9EHY1XeoMhgg',
    appId: '1:31010099352:android:f41fd45031bbf53dedc0ed',
    messagingSenderId: '31010099352',
    projectId: 'login-auth-eec5f',
    storageBucket: 'login-auth-eec5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG8Q9npDZ79TnHAEy8uEOJCUMsGsEqZGw',
    appId: '1:31010099352:ios:91d9ca71a011f25eedc0ed',
    messagingSenderId: '31010099352',
    projectId: 'login-auth-eec5f',
    storageBucket: 'login-auth-eec5f.appspot.com',
    iosClientId: '31010099352-0bjtquk65l7o8ndmch7m8end81kfp55a.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG8Q9npDZ79TnHAEy8uEOJCUMsGsEqZGw',
    appId: '1:31010099352:ios:91d9ca71a011f25eedc0ed',
    messagingSenderId: '31010099352',
    projectId: 'login-auth-eec5f',
    storageBucket: 'login-auth-eec5f.appspot.com',
    iosClientId: '31010099352-0bjtquk65l7o8ndmch7m8end81kfp55a.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
